---
version: 0.2

phases:
  install:
    commands:
# Installing newman CLI to do Automated Unit Testing
      - echo Installing newman CLI - `pwd`  
      - npm install -g newman
      - echo newman CLI Installation Completed  `date` in `pwd`
  build:
    commands:
# Running NewMan CLI   
      - echo Starting newman CLI Testing for SGW `date` in `pwd`
      - newman run StaycayGoWhere.postman_collection.json > newman-report.txt
      
artifacts:
  files: 'newman-report.txt'

